name: Validate Homey App
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    name: Test on Node.js 22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm test

  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified
